kind: pipeline
type: docker
name: default

steps:
- name: docker-build-and-push
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: yuknak/snn
    tags: 1.0.4

trigger:
  event:
    - push
  branch:
    - master
