AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'mobile/**/*'
    - 'vendor/**/*'
    #- 'db/**/*'
    #- 'config/**/*'
    #- 'script/**/*'
    #- 'bin/{rails,rake}'
    #- !ruby/regexp /old_and_unused\.rb$/

require:
  - rubocop-rails
  - rubocop-rspec
